# Generated by Django 3.1.2 on 2020-11-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='distance',
            field=models.FloatField(default=0),
        ),
    ]
